
public enum SubmenuOperacoes {
	CADASTRAR_CLIENTE,
	CADASTRAR_VEICULO,
	CADASTRAR_FROTA,
	CADASTRAR_SEGURADORA,
	LISTAR_CLIENTE,
	LISTAR_SINISTROS_POR_SEGURADORA,
	LISTAR_SINISTROS_POR_CLIENTE,
	LISTAR_VEICULO_POR_CLIENTE,
	LISTAR_VEICULO_POR_SEGURADORA,
	EXCLUIR_CLIENTE,
	EXCLUIR_VEICULO,
	EXCLUIR_SINISTRO,
	VOLTAR
}
