
public enum SubmenuOperacoes {
	CADASTRAR_CLIENTE,
	CADASTRAR_VEICULO,
	CADASTRAR_FROTA,
	CADASTRAR_SEGURADORA,
	GERAR_SEGURO,
	AUTORIZAR_CONDUTOR,
	DESAUTORIZAR_CONDUTOR,
	LISTAR_SEGURO_POR_CLIENTE,
	LISTAR_CONDUTOR_POR_SEGURO,
	LISTAR_FROTA_POR_CLIENTE,
	LISTAR_CLIENTE,
	LISTAR_SINISTROS_POR_SEGURADORA,
	LISTAR_SINISTROS_POR_CLIENTE,
	LISTAR_VEICULO_POR_CLIENTE,
	LISTAR_VEICULO_POR_SEGURADORA,
	EXCLUIR_CLIENTE,
	EXCLUIR_VEICULO,
	EXCLUIR_SINISTRO,
	VOLTAR
}
